### ISSUE TITLE
Uncaught (in promise) Error: Error: not allowed

### ISSUE THREAD

**Issue by rderocle-gsoi** [subscriptions-project/swg-js#2081]
Hello, when I run this code on my site

```
    (self.SWG = self.SWG || []).push(subscriptions => {
        subscriptions.init(PUBLICATION_ID);
    });
```

I encounter this error

```
activity-ports.js:75 Uncaught (in promise) Error: Error: not allowed
    at new za (activity-ports.js:75:13)
    at Pa.Ca (activity-ports.js:1053:24)
    at Oa.Ca (activity-ports.js:858:12)
    at Oa.Qd (activity-ports.js:821:10)
```

I loaded the swg.js with the option "subscriptions-control" to manual.

**Comment by jpettitt** [comment]
Can you give us a bit more info - what browser are you running?  Are you running on localhost or a domain?  Is the domain configured for swg in publisher center?  what is your publication id?

**Comment by rderocle-gsoi** [comment]
Hello, I'm testing on Chrome, with Tampermonkey extension.
Site: https://abonnement.sudouest.fr/
Code:
```
const PUBLICATION_ID = 'sudouest.fr';

const injectSwg = () => {
    const element = document.createElement('script');
    element.setAttribute('subscriptions-control', 'manual');
    element.setAttribute('async', '');
    element.setAttribute('src', '//news.google.com/swg/js/v1/swg.js');
    document.head.appendChild(element);
};

const setupSwg = () => {
    (self.SWG = self.SWG || []).push(function(subscriptions) {
        document.querySelectorAll('div[class=card-box__content]').forEach((node) => {
            const hr = document.createElement('hr');
            hr.setAttribute('style', 'width: 100% !important; border-top: 1px solid #444;');
            node.appendChild(hr);

            const btn = document.createElement('button');
            btn.setAttribute('class', 'swg-button');
            node.appendChild(btn);

            subscriptions.attachButton(btn, { theme: 'light', lang: 'fr' }, () => subscriptions.showOffers({ isClosable: true }));
        });

        subscriptions.init(PUBLICATION_ID);
    });
}

(function() {
    'use strict';

    injectSwg();
    setupSwg();
})();
```

**Comment by rderocle-gsoi** [comment]
![Screenshot_2022-01-17_11-01-35](https://user-images.githubusercontent.com/83579511/149748827-1b346792-902e-4d50-b21d-411b92da66ae.png)

**Comment by stddd** [comment]
Hello @rderocle-gsoi,

can u provide what was the solution for this error plz ? :) i have the same error 

Thanks !

**Comment by jpettitt** [comment]
@ChrisAntaki can you take a look at this?

@stddd what are you seeing in chrome dev tools?

**Comment by stddd** [comment]
of course!  thanks for the fast reply ! 
https://aboshop-test.lalibre.be
![image](https://user-images.githubusercontent.com/7623789/235198058-1112b3ac-bc45-444f-a664-9bc6a5aa1832.png)

**Comment by ChrisAntaki** [comment]
No problem! Could you verify "https://aboshop-test.lalibre.be" is an authorized origin?

**Comment by ChrisAntaki** [comment]
Could you try adding `https://aboshop-test.lalibre.be` as an additional website property URL in Publisher Center?
![image](https://user-images.githubusercontent.com/1216762/235204374-2866c29b-46cc-4a1a-9391-e4fbce220187.png)

After adding the URL, this issue should resolve after an hour or so ⌛

**Comment by ChrisAntaki** [comment]
Looks like it's working 🎉

**Comment by stddd** [comment]
Hello @ChrisAntaki ,
Sorry to disturb you again but the modification didn't seem to do the job :( 
![image](https://user-images.githubusercontent.com/7623789/235629734-69f86c17-4b57-40fd-97f8-1d165f0aee17.png)
Getting the same error, do you have any other solution ? 
Thanks !

**Comment by ChrisAntaki** [comment]
I'm glad to hear it's working!

> It seems that was a problem of sync call of the init() then the showOffer().

Just curious, could our documentation be clearer about this?

**Comment by stddd** [comment]
After trying to put the 'self' call in the DOM to try directly the library with no succes.
i tried to call via the Window property  `window: Window & typeof globalThis` (typed in Typescript)
and added the async await to the call throw the push function flow: 

`(window.SWG = window.SWG || []).push(async (subscriptions: any) => {
      await subscriptions.init();
      await subscriptions.attachButton(
        document.getElementById('swg-standard-button'),
        { theme: 'light', lang: 'fr' },
        async () => {
          await subscriptions.showOffers({ isClosable: true });
        }
      );`

Is it possible than the function of the swg script can be awaitable ?

**Comment by ChrisAntaki** [comment]
Something like this?

```
const subscriptions = await new Promise((res) => {
    (window.SWG = window.SWG || []).push(res);
});
```

**Comment by stddd** [comment]
It seems to work properly now ! :) 
Thanks !
